# -*- coding: utf-8 -*-
"""To-Do_List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhDcUlBp9Wy5uQGHIWqb2-Unga62nc3z
"""

# Name Surname: Elifnur Özçelik

import datetime
import pytz

# List to store all tasks
tasks = []


# Reads previously saved tasks from the file
def read_tasks():
    try:
        with open("tasks.txt", "r", encoding="utf-8") as file:
            for line in file:
                tasks.append(line.strip())
    except FileNotFoundError:
        pass  # If file doesn't exist, ignore

# Saves the task list to the file
def save_tasks():
    try:
        with open("tasks.txt", "w", encoding="utf-8") as file:
            for task in tasks:
                file.write(task + "\n")
    except Exception as e:
        print("Failed to save file", e)

# Prints all tasks with numbering
def list_tasks():
    if not tasks:
        print("Task list is empty.")
    else:
        print("Current Tasks:")
        for i, task in enumerate(tasks, start=1):
            print(f"{i}. {task}")

# Gets a new task from the user and adds it to the list
def add_task():
    new_task = input("Enter new task: ").strip()
    if new_task == "":
        print("Empty task cannot be added!")
    else:
        tasks.append(new_task)
        save_tasks()
        print("Task added.")

# Deletes the selected task from the list
def delete_task():
    list_tasks()
    if not tasks:
        return
    try:
        choice = int(input("Enter the number of the task to delete: "))
        if 1 <= choice <= len(tasks):
            deleted = tasks.pop(choice - 1)
            save_tasks()
            print(f"'{deleted}' task deleted.")
        else:
            print("Invalid task number.")
    except ValueError:
        print("Please enter a valid number.")

# Allows the user to edit the selected task
def edit_task():
    list_tasks()
    if not tasks:
        return
    try:
        choice = int(input("Enter the number of the task to edit: "))
        if 1 <= choice <= len(tasks):
            new_task = input("Enter the new task text: ").strip()
            if new_task == "":
                print("Empty task cannot be added!")
            else:
                tasks[choice - 1] = new_task  # Update the task
                save_tasks()
                print("Task updated.")
        else:
            print("Invalid task number.")
    except ValueError:
        print("Please enter a valid number.")

# Main menu: takes user's choice and runs the related function
def menu():
    read_tasks()
    while True:
        print("\n--- To-Do List ---")
        print("1. List Tasks")
        print("2. Add New Task")
        print("3. Edit Task")
        print("4. Delete Task")
        print("q. Quit")

        choice = input("Choose an option (1/2/3/4/q): ")

        if choice == '1':
            list_tasks()
        elif choice == '2':
            add_task()
        elif choice == '3':
            edit_task()
        elif choice == '4':
            delete_task()
        elif choice == 'q':
            print("Exiting...")
            break
        else:
            print("Invalid choice. Please try again.")

menu()